apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: messaging
    microname: rabbitmq
spec:
  selector:
    project: roboshop
    purpose: rsdemo
    tier: messaging
    microname: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: messaging
    microname: rabbitmq
spec:
  selector:
    project: roboshop
    purpose: rsdemo
    tier: messaging
    microname: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmqsecret
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: messaging
    microname: rabbitmq
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: messaging
    microname: rabbitmq
spec:
  serviceName: rabbitmq-headless
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      purpose: rsdemo
      tier: messaging
      microname: rabbitmq
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rsdemo
        tier: messaging
        microname: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3
          ports:
            - containerPort: 5672
          envFrom:
            - secretRef:
                name: rabbitmqsecret
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumeClaimTemplates:
        - metadata:
            name: rabbitmq-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "roboshop-ebs"
            resources:
              requests:
                storage: 2Gi
