apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: database
    microname: mongodb
spec:
  selector:
    project: roboshop
    purpose: rsdemo
    tier: database
    microname: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: database
    microname: mongodb
spec:
  selector:
    project: roboshop
    purpose: rsdemo
    tier: database
    microname: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: database
    microname: mongodb
spec:
  serviceName: mongodb-headless
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      purpose: rsdemo
      tier: database
      microname: mongodb
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rsdemo
        tier: database
        microname: mongodb
    spec:
      containers:
        - name: mongodb
          image: satyology/mongodboptimized
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
    volumeClaimTemplates:
      - metadata:
          name: mongodb-data
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "roboshop-ebs"
          resources:
            requests:
              storage: 2Gi
