apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: database
    microname: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      purpose: rsdemo
      tier: database
      microname: redis
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rsdemo
        tier: database
        microname: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: database
    microname: redis
spec:
  selector:
    project: roboshop
    purpose: rsdemo
    tier: database
    microname: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
